update kpm patch for sukisu

diff --git a/.github/workflows/Build SukiSU Ultra.yml b/.github/workflows/Build SukiSU Ultra.yml
--- a/.github/workflows/Build SukiSU Ultra.yml
+++ b/.github/workflows/Build SukiSU Ultra.yml
@@ -955,11 +955,17 @@ jobs:
         if: inputs.KPM
         run: |
           cd /dev/shm/kout/arch/arm64/boot
-          curl -LO https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.13.0/patch_linux
+          curl -LSs "https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/download/0.13.0/patch_linux" -o patch_linux
           chmod +x patch_linux
           ./patch_linux
-          rm -f Image
-          mv oImage Image
+          if [ -f oImage ]; then
+            rm -f Image
+            mv oImage Image
+            echo "✅ KPM patched"
+          else
+            echo "❌ KPM patch failed"
+            exit 1
+          fi
 
       - name: 🧠 Package AK3 ZIP
         id: create_zip
